### ISSUE TITLE
Error on askpass.exe

### ISSUE THREAD

**Issue by mrmckeb** [lukesampson/pshazz#24] opened 2015-10-23 11:48 UTC
I'm running Windows 10, PowerShell 5, and I get the following when I try to push to GitHub.

```
project branch $ git push
error: unable to read askpass response from 'C:\Users\username\appdata\local\scoop\apps\pshazz\0.2014.11.25\libexec\askpass.exe'
```

Let me know if there's anything else I can provide to help with troubleshooting.

**Comment by cardonator** [comment] 2015-12-12 23:40
askpass seems like it is in a broken state to me. Pshazz isn't loading ssh-agent at PS launch for me nor does ssh even try to use private key login it seems like ever since the last update I did a few weeks ago.

**Comment by philschonholzer** [comment] 2016-01-03 09:36
Got the same problem. Executing askpass.exe gives me also this:
```
Resize master = $ askpass

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at askpass.Program.Main(String[] args)
```

**Comment by lukesampson** [comment] 2016-01-03 11:37
`askpass.exe` is only really expecting to be called by `sshagent` (by setting the `$env:SSH_ASKPASS` variable)—so it's expecting `ssh_agent` to call it with a first argument like `"Enter passphrase for [username]"`. (source code for askpass.exe [here](https://github.com/lukesampson/askpass/blob/master/Program.cs))

So the `IndexOutOfRangeException` shouldn't really be a problem if `ssh_agent` is hooked up correctly, so maybe the problem is elsewhere.

Is `ssh` being loaded by your theme?

**Comment by ionTea** [comment] 2016-02-26 10:25
Hey, I get the same error message - these programs are installed in powershell (with scoop)
 7zip (15.14)                                                                                                 
concfg (0.2016.01.25)
coreutils (5.97.3)
curl (7.46.0)
go (1.6)
grep (2.5.4)
less (394)
nodejs (5.6.0)
openssh (5.4p1-1)
pshazz (0.2015.11.13)
sed (4.2.1) 
sudo (0.2014.07.18)
vim (7.4)

Is there any conflicts that i should be aware of?

**Comment by smeijer** [comment] 2018-06-07 13:32
Same problem as @philschonholzer. To exclude conflicts from @ionTea, I only have `concfg` installed.

```
Installed apps:
  concfg 0.2018.5.27
```

```
scoop install pshazz
```

```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at askpass.Program.Main(String[] args)
```

**Comment by mykolapolonskyi** [comment] 2018-06-07 14:08
![image](https://user-images.githubusercontent.com/7451751/41104879-1689097e-6a75-11e8-9704-5ec4042666f3.png) 
uninstall optional feature OpennSSH client helps solve issue -> powershell start to use ssh installed with scoop

**Comment by TCB13** [comment] 2018-08-26 23:10
@smeijer I'm having the same issue, check this: https://github.com/lukesampson/scoop/issues/2268#issuecomment-416078162

**Comment by vertexportus** [comment] 2018-10-18 22:14
is there a fix for this ?

**Comment by h404bi** [comment] 2018-10-19 02:18
If anyone want to avoid the problem temporarily, you could remove askpass.exe from `ssh.ps1` plugin but keep other functionality, like [ssh.ps1](https://github.com/h404bi/dotfiles/blob/master/src/pshazz/plugins/ssh.ps1). Then put it into `%USERPROFILE%\pshazz\plugins`.

**Comment by jwhipp** [comment] 2018-12-14 22:51
Having the same problem with askpass.exe, I decided to use this SSH config as a work around:

CLI: StrictHostKeyChecking=accept-new 
Config: StrictHostKeyChecking accept-new

I don't want to disable host key checking, and this is a bit of a compromise. It'll cause ssh accept new keys automatically but won't accept a host key that has changed.

**Comment by superdump** [comment] 2018-12-16 14:42
@jwhipp where do you put those configuration options?

**Comment by jwhipp** [comment] 2018-12-16 17:55
@superdump  

Here's how to use it: 

On the command line:

`ssh -o StrictHostKeyChecking=accept-new user@host`

In the config ~\.ssh\config:

```
Host *
    StrictHostKeyChecking accept-new
```

I just tossed it in the ~\.ssh\config.

**Closed** 2019-01-12 03:34 UTC
